In [1]:
# Broadcasting

import numpy as np

x = np.arange(10)
print(x)
x = x + 4
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11 12 13]


In [3]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

y = np.array([1, 2, 3, 4])

print(x + y)


[[ 2  4  6  8]
 [ 6  8 10 12]]


In [4]:
# element wise matrix multiplication ( O(n^2) )
# matrix multiplication ( O(n^3) )