# Working with numpy for numerical computation

In [1]:
!pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 46.0 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
# create a numpy array

In [5]:
a = np.array([1, 2, 3, 4])
print(a)
print(type(a))
print(a.shape)
print(a[1])

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
2


In [7]:
a = np.array([[1], [2], [3], [4]])
print(a)
print(type(a))
print(a.shape)
print(a[1][0])

[[1]
 [2]
 [3]
 [4]]
<class 'numpy.ndarray'>
(4, 1)
2


In [10]:
# zeros, ones, custom and random array

a = np.zeros((2, 3))
print(a)

b = np.ones((2, 3))
print(b)

c = np.full((2, 3), 4)
print(c)

d = np.random.random((2, 3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4 4]
 [4 4 4]]
[[0.9949694  0.66125175 0.87325634]
 [0.31022457 0.81048071 0.83066384]]


In [14]:
# selecting and updating using slice
a = np.zeros((3, 3), dtype=np.int64)
print(a)
a[1 , : ] = 5
print(a)
a[ : , -1] = 7
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [5 5 5]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [15]:
# datatypes
print(a.dtype)

int64


In [20]:
# Mathematical operations
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# addition
print(a + b)
print(np.add(a, b))

# subtraction
print(a - b)
print(np.subtract(a, b))

# multiplication
print(a * b)
print(np.multiply(a, b))

# division
print(a / b)
print(np.divide(a, b))

# sqrt
print(np.sqrt(a))



[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [21]:
# Matrix multiplication

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a.dot(b))
print(np.dot(a, b))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [22]:
# Vector Multiplication => Scalar
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]
print(np.dot(a, b))

30


In [24]:
a = [
        [1, 2],
        [3, 4],
]

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

10
[4 6]
[3 7]


In [29]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
b = b ** 2

print(np.stack((a, b), axis=0))
print(np.stack((a, b), axis = 1))

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [34]:
# reshape
x = np.stack((a, b), axis=0)
print(x)
print(x.shape)

y = x.reshape((4, 2))
print(y)
print(y.shape)

z = x.reshape((8, -1))
print(z)
print(z.shape)

[[ 1  2  3  4]
 [ 1  4  9 16]]
(2, 4)
[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
(4, 2)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]
(8, 1)
