# For working with random distribution we need numpy random module

In [2]:
import numpy as np

In [3]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [16]:
np.random.seed(1)

# shuffle
np.random.shuffle(a)
print(a)

# rand
a = np.random.rand(2, 3)
print(a)

# randn -> sample from normal distribution
a = np.random.randn(2, 3)
print(a)

# randint -> range and number of values to generate
a = np.random.randint(5, 10, 10)
print(a)

# choice -> randomly select a number
print(np.random.choice([2, 4, -9, 34, -100]))

[6 5 6 5 7 6 9 6 6 6]
[[0.38791074 0.66974604 0.93553907]
 [0.84631092 0.31327352 0.52454816]]
[[-1.50780766 -0.31529207  0.85817886]
 [ 0.07134299 -2.29230928 -1.41555249]]
[5 6 6 6 6 5 9 6 5 5]
34
